[project]
name = 'sheran_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.NFT_backed]
path = 'contracts/NFT_backed.clar'
clarity_version = 2
epoch = 2.5

[contracts.daily_withdrawal_limit_wallet]
path = 'contracts/daily_withdrawal_limit_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.distribution_fund]
path = 'contracts/distribution_fund.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_retrieval]
path = 'contracts/file_retrieval.clar'
clarity_version = 2
epoch = 2.5

[contracts.interest_rate_dynamics]
path = 'contracts/interest_rate_dynamics.clar'
clarity_version = 2
epoch = 2.5

[contracts.inventory_with_delegated_updates]
path = 'contracts/inventory_with_delegated_updates.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-based]
path = 'contracts/reputation-based.clar'
clarity_version = 2
epoch = 2.5

[contracts.resear]
path = 'contracts/resear.clar'
clarity_version = 2
epoch = 2.5

[contracts.result_calculation]
path = 'contracts/result_calculation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
